sudo: false

language: php

matrix:
  fast_finish: true
  include:
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: hhvm

install:
- composer install --dev

script:
- ./vendor/bin/phpunit
